name: maroro
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluentui_icons: ^1.0.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  provider: ^6.1.2
  get: ^4.6.6
  font_awesome_flutter: ^10.6.0
  permission_handler: ^11.3.1
  flutter_easyloading: ^3.0.5
  path: ^1.9.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  intl_phone_field: ^3.2.0
  country_state_city_picker: ^1.2.8
  dash_chat_2: ^0.0.21
  firebase_analytics: ^11.3.3
  delightful_toast: ^1.1.0
  get_it: ^8.0.0
  video_compress: ^3.1.0
  fluttertoast: ^8.2.2
  uuid: ^4.5.1
  table_calendar: ^3.0.9
  data_table_2: ^2.5.8
  intl: ^0.19.0
  audioplayers: ^6.1.0
  flutter_local_notifications: ^18.0.0
  http: ^1.1.0
  firebase_messaging: ^15.1.3
  shared_preferences: ^2.2.2
  agora_rtc_engine: ^6.1.0
  calendar_view: ^1.0.0
  flutter_chat_ui: ^1.6.6
  url_launcher: ^6.1.6
  jitsi_meet_wrapper: ^0.2.0+1
  chewie: ^1.8.5
  open_file: ^3.5.9
  photo_view: ^0.14.0
  video_player: ^2.7.0
  

 
  

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/the_logo.png"  # Use forward slashes for path

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/img/pam.jpg
    - assets/img/images.jpeg
    - assets/img/the_logo.png
    - assets/sound/game_over.mp3
    - assets/sound/click.mp3
    - assets/sound/power_up.mp3
    - assets/sound/sparkle.mp3
    - assets/sound/swoosh.mp3
    - assets/sound/thud.mp3
